In [1]:
import pandas as pd

# Without AIME25

In [2]:
best_eval_noaime25 = pd.read_csv("rebuttals/global_top_runs_no_aime25.csv")
best_eval_noaime25

,global_rank,step,eval/aime24_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,10,0.578125,0.765625,0.945312,0.453125,0.539062,71987.994438,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.656250
1,2,10,0.554688,0.757812,0.929688,0.460938,0.539062,71970.506332,rebuttal-deepscaler-grpo-vllm-math2_deepscaler...,0.648438
2,3,10,0.601562,0.789062,0.906250,0.453125,0.484375,59964.440829,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P16384...,0.646875
3,4,10,0.492188,0.750000,0.929688,0.453125,0.531250,68019.339350,rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P...,0.631250
4,5,10,0.539062,0.781250,0.921875,0.398438,0.515625,81108.320359,rebuttal-deepscaler-grpo-vllm-math2_deepscaler...,0.631250
5,6,10,0.515625,0.750000,0.898438,0.414062,0.539062,80794.382091,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.623437
6,7,10,0.515625,0.765625,0.906250,0.414062,0.500000,59691.741296,rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P...,0.620313
7,8,10,0.476562,0.765625,0.906250,0.414062,0.484375,67471.247277,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P4096-...,0.609375
8,9,40,0.437500,0.734375,0.906250,0.414062,0.515625,85056.687440,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.601562
9,10,20,0.500000,0.703125,0.929688,0.382812,0.484375,50859.120732,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.600000

In [3]:
best_eval_noaime25.iloc[0]["run"]

'rebuttal-deepscaler-grpo-math2_deepscaler40k-Qwen3-4B-P16384-B16-S1-std-scale_lr-l8192-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus64--1774570910'

The best run without considering AIME25 took ~20h, at the first eval step, and used:

- dataset: deepscaler40k
- population size: 16,384
- normalize-with-std
- max tokens: 8,192

The best run which considers AIME25 is the 3rd best run when not considering AIME25 - it is also significantly faster in training.

## Population Size = 4096

In [4]:
best_eval_noaime25_p4096 = pd.read_csv("rebuttals/global_top_runs_no_aime25_p4096.csv")
best_eval_noaime25_p4096

,global_rank,step,eval/aime24_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,10,0.492188,0.750000,0.929688,0.453125,0.531250,68019.339350,rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P...,0.631250
1,2,10,0.539062,0.781250,0.921875,0.398438,0.515625,81108.320359,rebuttal-deepscaler-grpo-vllm-math2_deepscaler...,0.631250
2,3,10,0.515625,0.750000,0.898438,0.414062,0.539062,80794.382091,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.623437
3,4,10,0.476562,0.765625,0.906250,0.414062,0.484375,67471.247277,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P4096-...,0.609375
4,5,40,0.437500,0.734375,0.906250,0.414062,0.515625,85056.687440,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.601562
5,6,20,0.500000,0.703125,0.929688,0.382812,0.484375,50859.120732,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.600000
6,7,30,0.460938,0.726562,0.921875,0.421875,0.453125,79315.800093,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.596875
7,8,20,0.367188,0.742188,0.921875,0.437500,0.445312,57877.497483,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.582812
8,9,30,0.382812,0.656250,0.921875,0.414062,0.500000,68912.757418,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.575000
9,10,10,0.398438,0.656250,0.906250,0.421875,0.484375,30882.112427,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.573438

In [5]:
best_eval_noaime25_p4096.iloc[0]["run"]

'rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P4096-B16-S1-std-scale_lr-l8192-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus16--1774607028'

In [6]:
print(f"Second best: {best_eval_noaime25_p4096.iloc[1]["run"]}")

Second best: rebuttal-deepscaler-grpo-vllm-math2_deepscaler40k-Qwen3-4B-P4096-B16-S1-std-scale_lr-l8192-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus16--1774607523

The best run without considering AIME25 and using population size 4096 took ~18h53m, at the first eval step, and used:

- dataset: orz57k
- population size: 4,096
- normalize-with-std
- max tokens: 8,192

It achieves the same average score as the second best run (which is identical, except that it uses deepscaler40k to train), but it takes around 13k seconds (~3h36m) less to train.

Moreover, the best run with population size 4,096 is the 4th best run overall (when not using AIME25), achieving 0.025 less in the composite score.

## Population Size = 256

In [7]:
best_eval_noaime25_p256 = pd.read_csv("rebuttals/global_top_runs_no_aime25_p256.csv")
best_eval_noaime25_p256

,global_rank,step,eval/aime24_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,20,0.304688,0.585938,0.882812,0.390625,0.406250,77536.849884,rebuttal-orz-math2_orz57k-Qwen3-4B-P256-B16-S1...,0.514062
1,2,20,0.281250,0.523438,0.835938,0.398438,0.382812,73887.221853,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.484375
2,3,10,0.179688,0.554688,0.851562,0.351562,0.359375,30395.005143,rebuttal-orz-math2_orz57k-Qwen3-4B-P256-B16-S1...,0.459375
3,4,10,0.265625,0.476562,0.828125,0.375000,0.343750,49427.423627,rebuttal-orz-math2_orz57k-Qwen3-4B-P256-B16-S1...,0.457813
4,5,20,0.257812,0.531250,0.781250,0.359375,0.335938,77018.234364,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.453125
5,6,10,0.210938,0.554688,0.804688,0.343750,0.320312,42411.108782,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.446875
6,7,20,0.171875,0.476562,0.781250,0.320312,0.312500,82151.408743,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.412500
7,8,10,0.179688,0.406250,0.726562,0.265625,0.273438,42515.569887,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.370312
8,9,10,0.125000,0.375000,0.781250,0.312500,0.234375,45304.601825,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.365625
9,10,20,0.148438,0.406250,0.726562,0.203125,0.265625,53303.459834,rebuttal-orz-math2_orz57k-Qwen3-4B-P256-B16-S1...,0.350000

In [8]:
best_eval_noaime25_p256.iloc[0]["run"]

'rebuttal-orz-math2_orz57k-Qwen3-4B-P256-B16-S1-std-scale_lr-l4096-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus1--1774479188'

The best run without considering AIME25 and using population size 256 took ~21h53m, at the second eval step, and used:

- dataset: orz57k
- population size: 256
- normalize-with-std
- max tokens: 4,096

The difference in composite score between smaller populations and larger populations is quite notable, with a difference of more than 0.1.

It must be noted that there is a certain bias: when training with a larger population sizes, it seems that the model learns to be more succint and more accurate. This means that as training progresses, training iterations last for less. With population size 256, the speed of learning falls, which means that none of the runs which used max tokens 8192 were able to finish.

## Without normalize-with-std

In [9]:
best_eval_noaime25_nostd = pd.read_csv("rebuttals/global_top_runs_no_aime25_no_std.csv")
best_eval_noaime25_nostd

,global_rank,step,eval/aime24_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,20,0.312500,0.546875,0.851562,0.335938,0.351562,78527.556858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.479687
1,2,20,0.257812,0.531250,0.781250,0.359375,0.335938,77018.234364,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.453125
2,3,20,0.218750,0.515625,0.843750,0.328125,0.304688,83791.016253,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.442188
3,4,10,0.242188,0.460938,0.757812,0.320312,0.296875,43661.811844,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.415625
4,5,20,0.171875,0.476562,0.781250,0.320312,0.312500,82151.408743,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.412500
5,6,20,0.179688,0.468750,0.789062,0.312500,0.296875,81981.648858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.409375
6,7,20,0.171875,0.445312,0.796875,0.281250,0.257812,84510.922853,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.390625
7,8,10,0.187500,0.398438,0.781250,0.265625,0.273438,46661.360457,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.381250
8,9,10,0.210938,0.406250,0.734375,0.281250,0.257812,44607.432420,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.378125
9,10,10,0.179688,0.406250,0.726562,0.265625,0.273438,42515.569887,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.370312

In [10]:
best_eval_noaime25_nostd.iloc[0]["run"]

'rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4B-P16384-B16-S1-no_std-scale_lr-l4096-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus64--1774570885'

The best run without considering AIME25 and without using std normalisation took 21h48m, at the second eval step, and used:

- dataset: orz57k
- population size: 16,384
- no normalize-with-std
- max tokens: 4,096

The difference in composite score between using normalize-with-std and not is extremely significant. Even at the largest population size, the composite score is smaller than a run using population size 256.

## Max Tokens = 4096

In [11]:
best_eval_noaime25_l4096 = pd.read_csv("rebuttals/global_top_runs_no_aime25_l4096.csv")
best_eval_noaime25_l4096

,global_rank,step,eval/aime24_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,40,0.437500,0.734375,0.906250,0.414062,0.515625,85056.687440,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.601562
1,2,20,0.500000,0.703125,0.929688,0.382812,0.484375,50859.120732,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.600000
2,3,20,0.414062,0.703125,0.929688,0.453125,0.492188,46286.973525,rebuttal-orz-math2_orz57k-Qwen3-4B-P16384-B16-...,0.598437
3,4,30,0.414062,0.726562,0.929688,0.437500,0.484375,64401.306834,rebuttal-orz-math2_orz57k-Qwen3-4B-P16384-B16-...,0.598437
4,5,30,0.460938,0.726562,0.921875,0.421875,0.453125,79315.800093,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.596875
5,6,40,0.421875,0.703125,0.921875,0.414062,0.515625,80392.484923,rebuttal-orz-math2_orz57k-Qwen3-4B-P16384-B16-...,0.595313
6,7,20,0.367188,0.742188,0.921875,0.437500,0.445312,57877.497483,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.582812
7,8,10,0.398438,0.710938,0.929688,0.429688,0.437500,47990.657471,rebuttal-deepscaler-math2_deepscaler40k-Qwen3-...,0.581250
8,9,10,0.398438,0.671875,0.929688,0.421875,0.453125,27516.261300,rebuttal-orz-math2_orz57k-Qwen3-4B-P16384-B16-...,0.575000
9,10,30,0.382812,0.656250,0.921875,0.414062,0.500000,68912.757418,rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S...,0.575000

In [12]:
best_eval_noaime25_l4096.iloc[0]["run"]

'rebuttal-orz-math2_orz57k-Qwen3-4B-P4096-B16-S1-std-scale_lr-l4096-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus16--1774478238'

The best run without considering AIME25 and using 4096 max tokens took 23h37m, at the fourth eval step, and used:

- dataset: orz57k
- population size: 4,096
- normalize-with-std
- max tokens: 4,096

By reducing max tokens, we observe that training can go for longer, but performance is hindered. 

Interestingly, the best run (which is identical to the second best run) use the medium poppulation size, with population size 16,384 achieving the second best score.

# Best Overall

It is important to note that the runs which use AIME25 are quite biased, since these runs were executed at the very end of the runsv (i.e contains many runs which didn't use normalize-with-std; those that didn't have normalize-with-std will be using max tokens = 8192, and many of these runs never even got to execute 1 eval loop). I personally think that the most representative results are those coming from the runs which didn't use AIME25 for eval.

In [13]:
best_eval = pd.read_csv("rebuttals/global_top_runs.csv")
best_eval

,global_rank,step,eval/aime24_mean_fitness,eval/aime25_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,10,0.601562,0.453125,0.789062,0.906250,0.453125,0.484375,59964.440829,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P16384...,0.614583
1,2,10,0.578125,0.367188,0.765625,0.945312,0.453125,0.539062,71987.994438,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.608073
2,3,10,0.554688,0.382812,0.757812,0.929688,0.460938,0.539062,71970.506332,rebuttal-deepscaler-grpo-vllm-math2_deepscaler...,0.604167
3,4,10,0.515625,0.445312,0.765625,0.906250,0.414062,0.500000,59691.741296,rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P...,0.591146
4,5,10,0.539062,0.390625,0.781250,0.921875,0.398438,0.515625,81108.320359,rebuttal-deepscaler-grpo-vllm-math2_deepscaler...,0.591146
5,6,10,0.492188,0.335938,0.750000,0.929688,0.453125,0.531250,68019.339350,rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P...,0.582031
6,7,10,0.476562,0.414062,0.765625,0.906250,0.414062,0.484375,67471.247277,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P4096-...,0.576823
7,8,10,0.515625,0.320312,0.750000,0.898438,0.414062,0.539062,80794.382091,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.572917
8,9,20,0.312500,0.203125,0.546875,0.851562,0.335938,0.351562,78527.556858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.433594
9,10,20,0.257812,0.187500,0.531250,0.781250,0.359375,0.335938,77018.234364,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.408854

In [14]:
best_eval.iloc[0]["run"]

'rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P16384-B16-S1-std-scale_lr-l8192-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus64--1774570928'

The best run considering AIME25 tok 16h39m, at the first eval step, and used:

- dataset: orz57k
- population size: 16,384
- normalize-with-std
- max tokens: 8192

## Population Size = 4096

In [15]:
best_eval_p4096 = pd.read_csv("rebuttals/global_top_runs_p4096.csv")
best_eval_p4096

,global_rank,step,eval/aime24_mean_fitness,eval/aime25_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,10,0.539062,0.390625,0.781250,0.921875,0.398438,0.515625,81108.320359,rebuttal-deepscaler-grpo-vllm-math2_deepscaler...,0.591146
1,2,10,0.492188,0.335938,0.750000,0.929688,0.453125,0.531250,68019.339350,rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P...,0.582031
2,3,10,0.476562,0.414062,0.765625,0.906250,0.414062,0.484375,67471.247277,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P4096-...,0.576823
3,4,10,0.515625,0.320312,0.750000,0.898438,0.414062,0.539062,80794.382091,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.572917
4,5,20,0.179688,0.140625,0.468750,0.789062,0.312500,0.296875,81981.648858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.364583
5,6,20,0.171875,0.109375,0.445312,0.796875,0.281250,0.257812,84510.922853,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.343750
6,7,10,0.210938,0.140625,0.406250,0.734375,0.281250,0.257812,44607.432420,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.338542
7,8,10,0.148438,0.109375,0.335938,0.742188,0.250000,0.234375,46114.465113,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.303385
8,9,0,0.195312,0.070312,0.367188,0.601562,0.257812,0.218750,12859.650287,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.285156
9,10,0,0.195312,0.070312,0.367188,0.601562,0.257812,0.218750,12920.861362,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.285156

In [16]:
best_eval_p4096.iloc[0]["run"]

'rebuttal-deepscaler-grpo-vllm-math2_deepscaler40k-Qwen3-4B-P4096-B16-S1-std-scale_lr-l8192-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus16--1774607523'

In [17]:
print(f"Second best: {best_eval_p4096.iloc[1]["run"]}")

Second best: rebuttal-orz-grpo-vllm-math2_orz57k-Qwen3-4B-P4096-B16-S1-std-scale_lr-l8192-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus16--1774607028

The best run using population size 4096 took 22h31m, at the first eval step, and used:

- dataset: deepscaler40k
- population size: 4,096
- normalize-with-std
- max tokens: 8,192

It achieves a slightly worse score than that with population size 16384, by around 0.023, ranking as the 5th best run overall.

## Population Size = 256

In [18]:
best_eval_p256 = pd.read_csv("rebuttals/global_top_runs_p256.csv")
best_eval_p256

,global_rank,step,eval/aime24_mean_fitness,eval/aime25_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,20,0.257812,0.187500,0.531250,0.781250,0.359375,0.335938,77018.234364,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.408854
1,2,20,0.171875,0.148438,0.476562,0.781250,0.320312,0.312500,82151.408743,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.368490
2,3,10,0.179688,0.117188,0.406250,0.726562,0.265625,0.273438,42515.569887,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.328125
3,4,10,0.125000,0.109375,0.375000,0.781250,0.312500,0.234375,45304.601825,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.322917
4,5,0,0.078125,0.101562,0.390625,0.625000,0.265625,0.273438,13800.418328,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.289062
5,6,0,0.078125,0.101562,0.390625,0.625000,0.265625,0.273438,13898.030092,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.289062
6,7,0,0.078125,0.101562,0.390625,0.625000,0.265625,0.273438,12779.242218,rebuttal-orz-grpo-math2_orz57k-Qwen3-4B-P256-B...,0.289062
7,8,0,0.078125,0.101562,0.390625,0.625000,0.265625,0.273438,12743.328576,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.289062
8,9,0,0.078125,0.101562,0.390625,0.625000,0.265625,0.273438,13839.364898,rebuttal-deepscaler-grpo-math2_deepscaler40k-Q...,0.289062
9,10,0,0.078125,0.101562,0.390625,0.625000,0.265625,0.273438,12817.764835,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.289062

In [19]:
best_eval_p256.iloc[0]["run"]

'rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4B-P256-B16-S1-no_std-scale_lr-l4096-n4-lr0.001-sigma0.001-r1-alpha1-seed0-gpus1--1774567856'

The best run using population size 256 took 21h23m, at the second eval step, and used:

- dataset: orz57k
- population size: 256
- no normalize-with-std
- max tokens: 4,096

Very interestingly, this run goes against the intuitions of all other runs (i.e in all other runs, the best scores were achieved by using normalize-with-std and 8192 max tokens).

The difference in composite score between smaller populations and larger populations is quite notable, with a difference of more than 0.2.

It must be noted that there is a certain bias: when training with a larger population sizes, it seems that the model learns to be more succint and more accurate. This means that as training progresses, training iterations last for less. With population size 256, the speed of learning falls, which means that none of the runs which used max tokens 8192 were able to finish.

## Without normalize-with-std

In [20]:
best_eval_nostd = pd.read_csv("rebuttals/global_top_runs_no_std.csv")
best_eval_nostd

,global_rank,step,eval/aime24_mean_fitness,eval/aime25_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,20,0.312500,0.203125,0.546875,0.851562,0.335938,0.351562,78527.556858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.433594
1,2,20,0.257812,0.187500,0.531250,0.781250,0.359375,0.335938,77018.234364,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.408854
2,3,20,0.218750,0.140625,0.515625,0.843750,0.328125,0.304688,83791.016253,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.391927
3,4,20,0.171875,0.148438,0.476562,0.781250,0.320312,0.312500,82151.408743,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.368490
4,5,10,0.242188,0.117188,0.460938,0.757812,0.320312,0.296875,43661.811844,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.365885
5,6,20,0.179688,0.140625,0.468750,0.789062,0.312500,0.296875,81981.648858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.364583
6,7,20,0.171875,0.109375,0.445312,0.796875,0.281250,0.257812,84510.922853,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.343750
7,8,10,0.210938,0.140625,0.406250,0.734375,0.281250,0.257812,44607.432420,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.338542
8,9,10,0.187500,0.109375,0.398438,0.781250,0.265625,0.273438,46661.360457,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.335938
9,10,10,0.179688,0.117188,0.406250,0.726562,0.265625,0.273438,42515.569887,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.328125

In [21]:
best_eval_nostd.iloc[0]["run"]

'rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4B-P16384-B16-S1-no_std-scale_lr-l4096-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus64--1774570885'

The best run without using std normalisation took 21h48m, at the second eval step, and used:

- dataset: orz57k
- population size: 16,384
- no normalize-with-std
- max tokens: 4,096

The difference in composite score between using normalize-with-std and not is extremely significant.

## Max Tokens = 4096

In [22]:
best_eval_l4096 = pd.read_csv("rebuttals/global_top_runs_l4096.csv")
best_eval_l4096

,global_rank,step,eval/aime24_mean_fitness,eval/aime25_mean_fitness,eval/amc_mean_fitness,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,training_time_s,run,composite_score
0,1,20,0.312500,0.203125,0.546875,0.851562,0.335938,0.351562,78527.556858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.433594
1,2,20,0.257812,0.187500,0.531250,0.781250,0.359375,0.335938,77018.234364,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.408854
2,3,20,0.218750,0.140625,0.515625,0.843750,0.328125,0.304688,83791.016253,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.391927
3,4,20,0.171875,0.148438,0.476562,0.781250,0.320312,0.312500,82151.408743,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.368490
4,5,10,0.242188,0.117188,0.460938,0.757812,0.320312,0.296875,43661.811844,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.365885
5,6,20,0.179688,0.140625,0.468750,0.789062,0.312500,0.296875,81981.648858,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.364583
6,7,20,0.171875,0.109375,0.445312,0.796875,0.281250,0.257812,84510.922853,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.343750
7,8,10,0.210938,0.140625,0.406250,0.734375,0.281250,0.257812,44607.432420,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.338542
8,9,10,0.187500,0.109375,0.398438,0.781250,0.265625,0.273438,46661.360457,rebuttal-deepscaler-grpo-no-norm-math2_deepsca...,0.335938
9,10,10,0.179688,0.117188,0.406250,0.726562,0.265625,0.273438,42515.569887,rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4...,0.328125

In [23]:
best_eval_l4096.iloc[0]["run"]

'rebuttal-orz-grpo-no-norm-math2_orz57k-Qwen3-4B-P16384-B16-S1-no_std-scale_lr-l4096-n4-lr0.0002-sigma0.001-r1-alpha1-seed0-gpus64--1774570885'

The best run without using 4096 max tokens took 21h48m, at the second eval step, and used:

- dataset: orz57k
- population size: 16,384
- no normalize-with-std
- max tokens: 4,096

It's the same as the analysis above from no normalize-with-std