In [1]:
import wandb

/lus/lfs1aip2/scratch/s5e/alv31415.s5e/uv_envs/vllm_env/.venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.5.0) or chardet (7.1.0)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [2]:
api = wandb.Api()
run = api.run("/alv31415/hyperscalees-vllm/runs/9pqxcwcl")

In [4]:
run.history()

KeyboardInterrupt


KeyboardInterrupt

In [9]:
run_history = run.history()

In [15]:
benchmarks = ["eval/math_mean_fitness",
              "eval/minerva_mean_fitness",
              "eval/olympiad_bench_mean_fitness", 
              "eval/aime24_mean_fitness", 
               "eval/aime25_mean_fitness", 
              ]

In [16]:
eval_history = run_history.loc[:, benchmarks]
eval_history

,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,eval/aime24_mean_fitness,eval/aime25_mean_fitness
0,0.617188,0.234375,0.265625,0.085938,0.109375
1,0.898438,0.429688,0.460938,0.507812,0.289062
2,0.898438,0.429688,0.445312,0.531250,0.335938
3,0.914062,0.445312,0.515625,0.546875,0.414062
4,0.929688,0.421875,0.476562,0.507812,0.437500

In [18]:
eval_history.T.mean()

0    0.262500
1    0.517188
2    0.528125
3    0.567187
4    0.554688
dtype: float64

In [19]:
orz_run = api.run("/alv31415/hyperscalees-vllm/runs/xt5whp77")

In [20]:
orz_run_history = orz_run.history()

In [21]:
orz_eval_history = orz_run_history.loc[:, benchmarks]
orz_eval_history

,eval/math_mean_fitness,eval/minerva_mean_fitness,eval/olympiad_bench_mean_fitness,eval/aime24_mean_fitness,eval/aime25_mean_fitness
0,0.617188,0.234375,0.265625,0.085938,0.109375
1,0.906250,0.421875,0.445312,0.382812,0.289062
2,0.898438,0.437500,0.476562,0.539062,0.343750
3,0.921875,0.468750,0.515625,0.546875,0.398438
4,0.898438,0.429688,0.539062,0.546875,0.421875